// examples/web-components/workspace-sidebar/src/outstanding-orders-card.ts
/*
 *  Copyright IBM Corp. 2026
 *
 *  This source code is licensed under the Apache-2.0 license found in the
 *  LICENSE file in the root directory of this source tree.
 *
 *  @license
 */

/**
 * OutstandingOrdersCard preview component.
 *
 * Demonstrates: a USER_DEFINED message rendered inline in the chat
 * transcript that previews outstanding orders and exposes a Maximize
 * action. Maximize invokes the `onMaximize` callback wired by main.ts,
 * which calls `instance.customPanels.getPanel(PanelType.WORKSPACE).open()`
 * with the card's `workspaceId` and `additionalData`.
 *
 * APIs exercised:
 *   - `<cds-aichat-card>` and `<cds-aichat-toolbar>`
 *   - User-defined response slot wiring via `onMaximize`
 *
 * Start reading at: `handleMaximize` and the `toolbarActions` array.
 */

import { LitElement, html, css } from "lit";
import { customElement, property } from "lit/decorators.js";
import "@carbon/ai-chat-components/es/components/card/index.js";
import "@carbon/ai-chat-components/es/components/toolbar/index.js";
import Maximize16 from "@carbon/icons/es/maximize/16.js";

@customElement("outstanding-orders-card")
export class OutstandingOrdersCard extends LitElement {
  static styles = css`
    :host {
      display: block;
    }

    .outstanding-orders-card-body {
      padding: 1rem;
    }

    .card-summary {
      margin-bottom: 1rem;
      color: #161616;
      font-weight: 500;
    }

    .card-preview {
      background: #f4f4f4;
      padding: 0.75rem;
      border-radius: 4px;
      margin-bottom: 1rem;
    }

    .preview-row {
      display: flex;
      justify-content: space-between;
      margin-bottom: 0.5rem;
    }

    .preview-row:last-child {
      margin-bottom: 0;
    }

    .preview-label {
      font-weight: 600;
      color: #525252;
    }

    .preview-value {
      color: #161616;
    }

    .card-hint {
      margin: 0;
      font-size: 0.875rem;
      color: #525252;
      font-style: italic;
    }
  `;

  @property({ type: String })
  accessor workspaceId = "";

  @property({ type: Object })
  accessor additionalData: any;

  @property({ type: Function })
  accessor onMaximize: (() => void) | undefined;

  @property({ type: Array })
  accessor toolbarActions: any[] = [
    {
      text: "Maximize",
      icon: Maximize16,
      size: "md",
      onClick: this.handleMaximize.bind(this),
    },
  ];

  private handleMaximize() {
    // Debug log so integrators can confirm the workspaceId being forwarded to customPanels.getPanel().open().
    console.log(
      "Maximize clicked, opening workspace with ID:",
      this.workspaceId,
    );
    // Defer to the parent-supplied onMaximize so the host owns the customPanels.getPanel(PanelType.WORKSPACE).open() call.
    if (this.onMaximize) {
      this.onMaximize();
    }
  }

  render() {
    return html`
      <cds-aichat-card is-flush>
        <div slot="header">
          <cds-aichat-toolbar overflow .actions=${this.toolbarActions}>
            <div slot="title">Outstanding Orders</div>
          </cds-aichat-toolbar>
        </div>
        <div slot="body" class="outstanding-orders-card-body">
          <p class="card-summary">
            You have 25 outstanding orders across multiple customers and
            products.
          </p>
          <div class="card-preview">
            <div class="preview-row">
              <span class="preview-label">Recent Orders:</span>
              <span class="preview-value">ORD-1025, ORD-1024, ORD-1023</span>
            </div>
            <div class="preview-row">
              <span class="preview-label">Total Value:</span>
              <span class="preview-value">$78,425.00</span>
            </div>
            <div class="preview-row">
              <span class="preview-label">Status:</span>
              <span class="preview-value">
                8 Pending, 7 Processing, 6 Shipped, 4 Delivered
              </span>
            </div>
          </div>
          <p class="card-hint">
            Click the maximize button to view all orders in detail.
          </p>
        </div>
      </cds-aichat-card>
    `;
  }
}

// Made with Bob

// examples/react/workspace/src/OutstandingOrdersCard.tsx
/*
 *  Copyright IBM Corp. 2026
 *
 *  This source code is licensed under the Apache-2.0 license found in the
 *  LICENSE file in the root directory of this source tree.
 *
 *  @license
 */

/**
 * User-defined response card for the workspace example.
 *
 * Demonstrates: a USER_DEFINED card rendered inline in the message stream that
 * exposes a Maximize action; its `onMaximize` callback is what `App.tsx` uses
 * to call `instance.customPanels.getPanel(PanelType.WORKSPACE).open(...)`.
 *
 * APIs exercised:
 *   - `Card`
 *   - `Toolbar`
 *
 * Start reading at: `OutstandingOrdersCard()` and the `handleMaximize` action.
 */

import React, { useState } from "react";
import Card from "@carbon/ai-chat-components/es/react/card.js";
import Toolbar from "@carbon/ai-chat-components/es/react/toolbar.js";
import Maximize16 from "@carbon/icons-react/es/Maximize.js";
import "./OutstandingOrdersCard.css";

interface OutstandingOrdersCardProps {
  workspaceId: string;
  onMaximize: () => void;
}

export function OutstandingOrdersCard({
  workspaceId,
  onMaximize,
}: OutstandingOrdersCardProps) {
  const handleMaximize = () => {
    console.log("Maximize clicked, opening workspace with ID:", workspaceId);
    onMaximize();
  };

  const [toolbarActions] = useState([
    {
      text: "Maximize",
      icon: Maximize16,
      size: "sm",
      onClick: handleMaximize,
    },
  ]);

  return (
    <Card isFlush>
      <div slot="header">
        <Toolbar overflow actions={toolbarActions}>
          <div slot="title">Outstanding Orders</div>
        </Toolbar>
      </div>
      <div slot="body" className="outstanding-orders-card-body">
        <p className="outstanding-orders-card-summary">
          You have 25 outstanding orders across multiple customers and products.
        </p>
        <div className="outstanding-orders-card-preview">
          <div className="preview-row">
            <span className="preview-label">Recent Orders:</span>
            <span className="preview-value">ORD-1025, ORD-1024, ORD-1023</span>
          </div>
          <div className="preview-row">
            <span className="preview-label">Total Value:</span>
            <span className="preview-value">$78,425.00</span>
          </div>
          <div className="preview-row">
            <span className="preview-label">Status:</span>
            <span className="preview-value">
              8 Pending, 7 Processing, 6 Shipped, 4 Delivered
            </span>
          </div>
        </div>
        <p className="outstanding-orders-card-hint">
          Click the maximize button to view all orders in detail.
        </p>
      </div>
    </Card>
  );
}

// Made with Bob
