// demo/src/web-components/custom-footer-example.ts
/*
 *  Copyright IBM Corp. 2026
 *
 *  This source code is licensed under the Apache-2.0 license found in the
 *  LICENSE file in the root directory of this source tree.
 *
 *  @license
 */

import { GenericItem } from "@carbon/ai-chat";
import { html, LitElement } from "lit";
import { customElement, property } from "lit/decorators.js";
import "@carbon/web-components/es/components/icon-button/index.js";
import { iconLoader } from "@carbon/web-components/es/globals/internal/icon-loader.js";
import Copy16 from "@carbon/icons/es/copy/16.js";
import Export16 from "@carbon/icons/es/export/16.js";
import Renew16 from "@carbon/icons/es/renew/16.js";

@customElement("custom-footer-example")
class CustomFooterExample extends LitElement {
  @property({ type: Object })
  accessor messageItem!: GenericItem;

  @property({ type: Object })
  accessor additionalData: Record<string, unknown> | undefined = undefined;

  connectedCallback() {
    super.connectedCallback();
  }

  disconnectedCallback() {
    super.disconnectedCallback();
  }

  private handleCopy = () => {
    let textToCopy = "";
    if (
      "text" in this.messageItem &&
      typeof this.messageItem.text === "string"
    ) {
      textToCopy = this.messageItem.text;
    }

    if (textToCopy) {
      navigator.clipboard.writeText(textToCopy);
    }
  };

  private handleRegenerate = () => {
    window.alert("Regenerate response clicked");
  };

  private handleShare = () => {
    const url = this.additionalData?.custom_action_url as string;
    if (url) {
      window.open(url, "_blank");
    }
  };

  render() {
    return html`
      <div class="custom-footer-actions">
        ${this.additionalData?.allow_copy
          ? html`
              <cds-icon-button
                class="custom-footer-button"
                align="top-left"
                kind="ghost"
                role="button"
                size="sm"
                @click=${this.handleCopy}
              >
                <span slot="icon">${iconLoader(Copy16)}</span>
                <span slot="tooltip-content">Copy</span>
              </cds-icon-button>
            `
          : null}
        ${this.additionalData?.allow_regenerate
          ? html`
              <cds-icon-button
                class="custom-footer-button"
                align="top-left"
                kind="ghost"
                role="button"
                size="sm"
                @click=${this.handleRegenerate}
              >
                <span slot="icon">${iconLoader(Renew16)}</span>
                <span slot="tooltip-content">Regenerate</span>
              </cds-icon-button>
            `
          : null}
        ${this.additionalData?.custom_action_url
          ? html`
              <cds-icon-button
                class="custom-footer-button"
                align="top-left"
                kind="ghost"
                role="button"
                size="sm"
                @click=${this.handleShare}
              >
                <span slot="icon">${iconLoader(Export16)}</span>
                <span slot="tooltip-content">Share</span>
              </cds-icon-button>
            `
          : null}
      </div>
    `;
  }
}

export default CustomFooterExample;

// demo/src/react/CustomFooterExample.tsx
/*
 *  Copyright IBM Corp. 2026
 *
 *  This source code is licensed under the Apache-2.0 license found in the
 *  LICENSE file in the root directory of this source tree.
 *
 *  @license
 */

import React from "react";
import { ChatInstance, MessageResponse, GenericItem } from "@carbon/ai-chat";
import { IconButton } from "@carbon/react";

// Using @carbon/icons-react for all icons
import Copy16 from "@carbon/icons-react/es/Copy.js";
import Export16 from "@carbon/icons-react/es/Export.js";
import Renew16 from "@carbon/icons-react/es/Renew.js";

interface CustomFooterExampleProps {
  slotName: string;
  message: MessageResponse;
  messageItem: GenericItem;
  instance: ChatInstance;
  additionalData?: Record<string, unknown>;
}

function CustomFooterExample({
  messageItem,
  additionalData,
}: CustomFooterExampleProps) {
  const handleCopy = () => {
    let textToCopy = "";
    if ("text" in messageItem && typeof messageItem.text === "string") {
      textToCopy = messageItem.text;
    }
    if (textToCopy) {
      navigator.clipboard.writeText(textToCopy);
    }
  };

  const handleRegenerate = () => {
    window.alert("Regenerate response clicked");
  };

  const handleShare = () => {
    const url = additionalData?.custom_action_url as string;
    if (url) {
      window.open(url, "_blank");
    }
  };

  return (
    <div className="custom-footer-actions">
      {Boolean(additionalData?.allow_copy) && (
        <IconButton
          className="custom-footer-button"
          align="top-left"
          kind="ghost"
          label="Copy"
          size="sm"
          onClick={handleCopy}
        >
          <Copy16 />
        </IconButton>
      )}
      {Boolean(additionalData?.allow_regenerate) && (
        <IconButton
          className="custom-footer-button"
          align="top-left"
          kind="ghost"
          label="Regenerate"
          size="sm"
          onClick={handleRegenerate}
        >
          <Renew16 />
        </IconButton>
      )}
      {Boolean(additionalData?.custom_action_url) && (
        <IconButton
          className="custom-footer-button"
          align="top-left"
          kind="ghost"
          label="Share"
          size="sm"
          onClick={handleShare}
        >
          <Export16 />
        </IconButton>
      )}
    </div>
  );
}

export { CustomFooterExample };
