// demo/src/react/DemoApp.tsx
/*
 *  Copyright IBM Corp. 2025
 *
 *  This source code is licensed under the Apache-2.0 license found in the
 *  LICENSE file in the root directory of this source tree.
 *
 *  @license
 */

import "./DemoApp.css";
import "@carbon/styles/css/styles.css";

import {
  BusEvent,
  BusEventMessageItemCustom,
  BusEventType,
  BusEventViewChange,
  BusEventViewPreChange,
  BusEventWorkspaceOpen,
  ChatContainer,
  ChatCustomElement,
  ChatInstance,
  FeedbackInteractionType,
  PublicConfig,
  RenderUserDefinedState,
  ServiceDesk,
  ServiceDeskFactoryParameters,
} from "@carbon/ai-chat";
import { AISkeletonPlaceholder } from "@carbon/react";
import React, { useCallback, useEffect, useMemo, useState } from "react";

import { Settings } from "../framework/types";
import { UserDefinedResponseExample } from "./UserDefinedResponseExample";
import { WriteableElementExample } from "./WriteableElementExample";
import { WorkspaceWriteableElementExample } from "./WorkspaceWriteableElementExample";
import { MockServiceDesk } from "../mockServiceDesk/mockServiceDesk";

const sleep = (milliseconds: number) =>
  new Promise((resolve) => setTimeout(resolve, milliseconds));

const serviceDeskFactory = (parameters: ServiceDeskFactoryParameters) =>
  Promise.resolve(new MockServiceDesk(parameters) as ServiceDesk);

interface AppProps {
  config: PublicConfig;
  settings: Settings;
  onChatInstanceReady?: (instance: ChatInstance) => void;
}

function DemoApp({ config, settings, onChatInstanceReady }: AppProps) {
  const [sideBarOpen, setSideBarOpen] = useState(false);
  const [sideBarClosing, setSideBarClosing] = useState(false);
  const [instance, setInstance] = useState<ChatInstance | null>(null);
  const [stateText, setStateText] = useState<string>("Initial text");
  const isSidebarLayout = settings.layout === "sidebar";

  useEffect(() => {
    setInterval(() => setStateText(Date.now().toString()), 2000);
  }, []);

  /**
   * Handler for user_defined response types. You can just have a switch statement here and return the right component
   * depending on which component should be rendered.
   */
  const renderUserDefinedResponse = useCallback(
    (state: RenderUserDefinedState, _instance: ChatInstance) => {
      const { messageItem, partialItems } = state;
      // The event here will contain details for each user defined response that needs to be rendered.
      if (messageItem) {
        switch (messageItem.user_defined?.user_defined_type) {
          case "green":
            return (
              <UserDefinedResponseExample
                text={messageItem.user_defined.text as string}
                parentStateText={stateText}
              />
            );
          case "response-stopped":
            return <>Custom user_defined response stopped message.</>;
          default:
            return undefined;
        }
      }

      if (partialItems) {
        switch (partialItems[0].user_defined?.user_defined_type) {
          case "green": {
            // The partial members are not concatenated, you get a whole array of chunks so you can special handle
            // concatenation as you want.
            const text = partialItems
              .map((item) => item.user_defined?.text)
              .join("");
            return (
              <UserDefinedResponseExample
                text={text}
                parentStateText={stateText}
              />
            );
          }
          default: {
            // Default to just showing a skeleton state for user_defined responses types we don't want to have special
            // streaming behavior for.
            return <AISkeletonPlaceholder className="fullSkeleton" />;
          }
        }
      }
    },
    [stateText],
  );

  /**
   * You can return a React element for each writeable element.
   */
  const allWriteableElements = useMemo(
    () => ({
      headerBottomElement: (
        <WriteableElementExample
          location="headerBottomElement"
          parentStateText={stateText}
        />
      ),
      welcomeNodeBeforeElement: (
        <WriteableElementExample
          location="welcomeNodeBeforeElement"
          parentStateText={stateText}
        />
      ),
      homeScreenHeaderBottomElement: (
        <WriteableElementExample
          location="homeScreenHeaderBottomElement"
          parentStateText={stateText}
        />
      ),
      homeScreenAfterStartersElement: (
        <WriteableElementExample
          location="homeScreenAfterStartersElement"
          parentStateText={stateText}
        />
      ),
      beforeInputElement: (
        <WriteableElementExample
          location="beforeInputElement"
          parentStateText={stateText}
        />
      ),
      aiTooltipAfterDescriptionElement: (
        <WriteableElementExample
          location="aiTooltipAfterDescriptionElement"
          parentStateText={stateText}
        />
      ),
      workspacePanelElement: (
        <WorkspaceWriteableElementExample
          location="workspacePanelElement"
          instance={instance as ChatInstance}
          parentStateText={stateText}
        />
      ),
    }),
    [stateText, instance],
  );

  /**
   * Determines which writeable elements to render based on settings and config.
   * - If writeableElements is true: show all elements
   * - If writeableElements is false AND homescreen is custom: show only home screen specific elements
   * - Otherwise: show no elements
   */
  const renderWriteableElements = useMemo(() => {
    const isCustomHomeScreen = config.homescreen?.customContentOnly === true;
    const showAllWriteableElements = settings.writeableElements === "true";
    const showHomeScreenElements =
      !showAllWriteableElements && isCustomHomeScreen;

    let elements;

    if (showAllWriteableElements) {
      elements = allWriteableElements;
    } else if (showHomeScreenElements) {
      elements = {
        homeScreenHeaderBottomElement:
          allWriteableElements.homeScreenHeaderBottomElement,
        homeScreenAfterStartersElement:
          allWriteableElements.homeScreenAfterStartersElement,
      };
    } else {
      elements = {};
    }

    return {
      ...elements,
      workspacePanelElement: allWriteableElements.workspacePanelElement,
    };
  }, [allWriteableElements, settings.writeableElements, config.homescreen]);

  const onBeforeRender = (instance: ChatInstance) => {
    setInstance(instance);
    // Notify parent component that instance is ready
    onChatInstanceReady?.(instance);

    // Here we are registering an event listener for if someone clicks on a button that throws
    // a client side event.
    instance.on({
      type: BusEventType.MESSAGE_ITEM_CUSTOM,
      handler: customButtonHandler,
    });

    // here we add a handler to the workspace pre open and open events
    instance.on({
      type: BusEventType.WORKSPACE_PRE_OPEN,
      handler: customWorkspacehandler,
    });

    instance.on({
      type: BusEventType.WORKSPACE_OPEN,
      handler: customWorkspacehandler,
    });

    // Handle feedback event.
    instance.on({ type: BusEventType.FEEDBACK, handler: feedbackHandler });
  };

  /**
   * Listens for view changes on the AI chat.
   */
  const onViewChange = isSidebarLayout
    ? (event: BusEventViewChange, _instance: ChatInstance) => {
        if (event.newViewState.mainWindow) {
          setSideBarOpen(true);
        } else {
          setSideBarOpen(false);
          setSideBarClosing(false);
        }
      }
    : undefined;

  /**
   * Handles pre-view-change lifecycle for sidebar transitions.
   */
  const onViewPreChange = isSidebarLayout
    ? async (event: BusEventViewPreChange, _instance: ChatInstance) => {
        if (!event.newViewState.mainWindow) {
          setSideBarClosing(true);
          await sleep(250);
        }
      }
    : undefined;

  // And some logic to add the right classname to our custom element depending on what mode we are in.
  let className = "";
  if (
    settings.layout === "fullscreen" ||
    settings.layout === "fullscreen-no-gutter"
  ) {
    className = "fullScreen";
  } else if (isSidebarLayout) {
    className = "sidebar";
    if (sideBarClosing) {
      className += " sidebar--closing";
    } else if (!sideBarOpen) {
      className += " sidebar--closed";
    }
  }

  return settings.layout === "float" ? (
    <ChatContainer
      {...config}
      onBeforeRender={onBeforeRender}
      renderUserDefinedResponse={renderUserDefinedResponse}
      renderWriteableElements={renderWriteableElements}
      serviceDeskFactory={serviceDeskFactory}
    />
  ) : (
    <ChatCustomElement
      {...config}
      className={className as string}
      onViewPreChange={onViewPreChange}
      onViewChange={onViewChange}
      onBeforeRender={onBeforeRender}
      renderUserDefinedResponse={renderUserDefinedResponse}
      renderWriteableElements={renderWriteableElements}
      serviceDeskFactory={serviceDeskFactory}
    />
  );
}

/**
 * Handles when the user submits feedback.
 */
function feedbackHandler(event: any) {
  if (event.interactionType === FeedbackInteractionType.SUBMITTED) {
    const { ...reportData } = event;
    setTimeout(() => {
      // eslint-disable-next-line no-alert
      window.alert(JSON.stringify(reportData, null, 2));
    });
  }
}

/**
 * Listens for clicks from buttons with custom events attached.
 */
function customButtonHandler(event: BusEvent) {
  const { messageItem } = event as BusEventMessageItemCustom;
  // The 'custom_event_name' property comes from the button response type with button_type of custom_event.
  if (messageItem.custom_event_name === "alert_button") {
    // eslint-disable-next-line no-alert
    window.alert(messageItem.user_defined?.text);
  }
}

/**
 * Listens for workspace panel open event.
 */
function customWorkspacehandler(event: BusEvent) {
  const { data } = event as BusEventWorkspaceOpen;
  console.log(data, "data");
}

export { DemoApp };

// demo/src/web-components/demo-app.ts
/*
 *  Copyright IBM Corp. 2025
 *
 *  This source code is licensed under the Apache-2.0 license found in the
 *  LICENSE file in the root directory of this source tree.
 *
 *  @license
 */

import "@carbon/web-components/es/components/ai-skeleton/index.js";
import "@carbon/ai-chat/dist/es/web-components/cds-aichat-container/index.js";
import "@carbon/ai-chat/dist/es/web-components/cds-aichat-custom-element/index.js";
import "./user-defined-response-example";
import "./writeable-element-example";

import {
  BusEvent,
  BusEventMessageItemCustom,
  BusEventType,
  BusEventViewChange,
  BusEventViewPreChange,
  ChatInstance,
  GenericItem,
  MessageResponse,
  PublicConfig,
  ServiceDesk,
  ServiceDeskFactoryParameters,
  UserDefinedItem,
  ViewType,
} from "@carbon/ai-chat";
import { css, html, LitElement, PropertyValues } from "lit";
import { customElement, property, state } from "lit/decorators.js";
import { DeepPartial } from "../types/DeepPartial";

import { Settings } from "../framework/types";
import { MockServiceDesk } from "../mockServiceDesk/mockServiceDesk";

async function sleep(milliseconds: number) {
  await new Promise((resolve) => {
    setTimeout(resolve, milliseconds);
  });
}

const serviceDeskFactory = (parameters: ServiceDeskFactoryParameters) =>
  Promise.resolve(new MockServiceDesk(parameters) as ServiceDesk);

interface UserDefinedSlotsMap {
  [key: string]: UserDefinedSlot;
}

interface UserDefinedSlot {
  streaming: boolean;
  message?: GenericItem;
  fullMessage?: MessageResponse;
  messageItem?: DeepPartial<GenericItem>;
  partialItems?: GenericItem[];
}

/**
 * `DemoApp` is a custom Lit element representing usage of AI chat with a web component.
 */
@customElement("demo-app")
export class DemoApp extends LitElement {
  static styles = css`
    cds-ai-skeleton-placeholder {
      width: 100%;
    }

    .fullScreen {
      position: fixed;
      bottom: 0;
      right: 0;
      height: calc(100vh - 48px);
      /* width: calc(100vw - 320px - 2rem); */
      width: 100%;
      z-index: 9999;
    }

    .sidebar {
      position: fixed;
      right: 0;
      top: 48px;
      height: calc(100vh - 48px);
      width: calc(320px + 1rem);
      z-index: 9999;
      transition: right 200ms;
      visibility: visible;
    }

    .sidebar--closing {
      right: calc(calc(320px + 1rem) * -1);
    }

    .sidebar--closed {
      right: calc(calc(320px + 1rem) * -1);
      visibility: hidden;
    }
  `;

  @property({ type: Object })
  accessor settings!: Settings;

  @property({ type: Object })
  accessor config!: PublicConfig;

  @property({ type: Object })
  accessor onChatInstanceReady: ((instance: ChatInstance) => void) | undefined =
    undefined;

  @state()
  accessor sideBarOpen: boolean = false;

  @state()
  accessor sideBarClosing: boolean = false;

  @state()
  accessor instance!: ChatInstance;

  @state()
  accessor userDefinedSlotsMap: UserDefinedSlotsMap = {};

  @state()
  accessor valueFromParent: string = Date.now().toString();

  private _interval?: ReturnType<typeof setInterval>;

  protected firstUpdated(_changedProperties: PropertyValues): void {
    this._interval = setInterval(() => {
      this.valueFromParent = Date.now().toString();
    }, 1500);
  }

  disconnectedCallback(): void {
    super.disconnectedCallback();
    if (this._interval) {
      clearInterval(this._interval);
    }
  }

  /**
   * Listens for view changes on the AI chat.
   */
  onViewPreChange = async (
    event: BusEventViewPreChange,
    _instance: ChatInstance,
  ) => {
    if (!event.newViewState.mainWindow) {
      this.sideBarClosing = true;
      // In production, should really be using AnimationEvent event here instead of a hard coded timeout.
      await sleep(250);
    }
  };

  /**
   * Listens for view changes on the AI chat.
   */
  onViewChange = (event: BusEventViewChange, _instance: ChatInstance) => {
    if (event.newViewState.mainWindow) {
      this.sideBarOpen = true;
    } else {
      this.sideBarOpen = false;
      this.sideBarClosing = false;
    }
  };

  /**
   * Closes/hides the chat.
   */
  openSideBar = () => {
    this.instance?.changeView(ViewType.MAIN_WINDOW);
  };

  /**
   * Listens for clicks from buttons with custom events attached.
   */
  customButtonHandler = (event: BusEvent) => {
    const { messageItem } = event as BusEventMessageItemCustom;
    // The 'custom_event_name' property comes from the button response type with button_type of custom_event.
    if (messageItem.custom_event_name === "alert_button") {
      // eslint-disable-next-line no-alert
      window.alert(messageItem.user_defined?.text);
    }
  };

  /**
   * The onBeforeRender prop lets as setup our event handlers and set the instance to state so we can access it
   * whenever we need to later.
   */
  onBeforeRender = (instance: ChatInstance) => {
    this.instance = instance;

    // Notify parent component that instance is ready
    this.onChatInstanceReady?.(instance);

    this.instance.on({
      type: BusEventType.MESSAGE_ITEM_CUSTOM,
      handler: this.customButtonHandler,
    });
    this.instance.on({
      type: BusEventType.USER_DEFINED_RESPONSE,
      handler: this.userDefinedHandler,
    });
    this.instance.on({
      type: BusEventType.CHUNK_USER_DEFINED_RESPONSE,
      handler: this.userDefinedHandler,
    });
    instance.on({
      type: BusEventType.WORKSPACE_PRE_OPEN,
      handler: (e) => console.log("pre open", e),
    });
    instance.on({
      type: BusEventType.WORKSPACE_OPEN,
      handler: (e) => console.log("open", e),
    });
  };

  /**
   * Each user defined event is tied to a slot deeply rendered with-in AI chat that is generated at runtime.
   * Here we make sure we store all these slots along with their relevant data in order to be able to dynamically
   * render the content to be slotted when this.renderUserDefinedSlots() is called in the render function.
   */
  userDefinedHandler = (event: any) => {
    const { data } = event;

    // Initialize or update the slot
    const existingSlot = this.userDefinedSlotsMap[data.slot];
    const isStreaming = Boolean(data.chunk);

    if (isStreaming && data.messageItem) {
      // For streaming, accumulate partial items
      const existingPartialItems = existingSlot?.partialItems || [];
      const newPartialItems = [...existingPartialItems, data.messageItem];
      this.userDefinedSlotsMap[data.slot] = {
        streaming: Boolean(newPartialItems.length),
        message: data.message,
        fullMessage: data.fullMessage,
        messageItem: data.messageItem,
        partialItems: newPartialItems,
      };
    } else {
      // For complete responses
      this.userDefinedSlotsMap[data.slot] = {
        streaming: Boolean(existingSlot?.partialItems?.length),
        message: data.message,
        fullMessage: data.fullMessage,
        messageItem: data.messageItem,
        partialItems: existingSlot?.partialItems,
      };
    }

    this.requestUpdate();
  };

  /**
   * This renders each of the dynamically generated slots that were generated by the AI chat by calling
   * this.renderUserDefinedResponse on each one.
   */
  renderUserDefinedSlots() {
    const userDefinedSlotsKeyArray = Object.keys(this.userDefinedSlotsMap);
    return userDefinedSlotsKeyArray.map((slot) => {
      return this.userDefinedSlotsMap[slot].streaming
        ? this.renderUserDefinedChunk(slot)
        : this.renderUserDefinedResponse(slot);
    });
  }

  /**
   * Here we process a single item from this.userDefinedSlotsMap. We go ahead and use a switch statement to decide
   * which element we should be rendering.
   */
  renderUserDefinedResponse(slot: keyof UserDefinedSlotsMap) {
    const { message } = this.userDefinedSlotsMap[slot];

    const userDefinedMessage = message as UserDefinedItem;

    // Check the "type" we have used as our key.
    switch (userDefinedMessage.user_defined?.user_defined_type) {
      case "green":
        // And here is an example using your own component.
        return html`<div slot=${slot}>
          <user-defined-response-example
            .text=${userDefinedMessage.user_defined.text as string}
            .valueFromParent=${this.valueFromParent}
          ></user-defined-response-example>
        </div>`;
      default:
        return null;
    }
  }

  /**
   * Here we process a single item from this.userDefinedSlotsMap. We go ahead and use a switch statement to decide
   * which element we should be rendering.
   */
  renderUserDefinedChunk(slot: keyof UserDefinedSlotsMap) {
    const { messageItem, partialItems } = this.userDefinedSlotsMap[slot];

    if (partialItems && partialItems.length > 0) {
      switch (partialItems[0].user_defined?.user_defined_type) {
        case "green": {
          // The partial members are not concatenated, you get a whole array of chunks so you can special handle
          // concatenation as you want.
          const text = partialItems
            .map((item) => item.user_defined?.text)
            .join("");
          return html`<div slot=${slot}>
            <user-defined-response-example
              .text=${text}
              .valueFromParent=${this.valueFromParent}
            ></user-defined-response-example>
          </div>`;
        }
        default: {
          // Default to just showing a skeleton state for user_defined responses types we don't want to have special
          // streaming behavior for.
          return html`<div slot=${slot}>
            <cds-ai-skeleton-text></cds-ai-skeleton-text>
          </div>`;
        }
      }
    }

    switch (messageItem?.user_defined?.user_defined_type) {
      default:
        // We are just going to always return a skeleton here, but you can give yourself more fine grained control.
        return html`<div slot=${slot}>
          <cds-ai-skeleton-text></cds-ai-skeleton-text>
        </div>`;
    }
  }

  /**
   * You only need to provide slots for the writable elements you want to use. In this demo, we fill them all with big
   * green boxes.
   */
  renderWriteableElementSlots() {
    if (!this.instance?.writeableElements) {
      return null;
    }

    const isCustomHomeScreen =
      this.config.homescreen?.customContentOnly === true;
    const showAllWriteableElements = this.settings.writeableElements === "true";
    const showHomeScreenElements =
      !showAllWriteableElements && isCustomHomeScreen;

    if (showAllWriteableElements) {
      // Show all writeable elements
      return Object.keys(this.instance.writeableElements).map((key) => {
        return html`<div slot=${key}>
          <writeable-element-example
            location=${key}
            valueFromParent=${this.valueFromParent}
          ></writeable-element-example>
        </div>`;
      });
    } else if (showHomeScreenElements) {
      // Show only home screen specific elements
      const homeScreenElementKeys = [
        "homeScreenHeaderBottomElement",
        "homeScreenAfterStartersElement",
      ];
      return homeScreenElementKeys
        .filter((key) => key in this.instance.writeableElements)
        .map((key) => {
          return html`<div slot=${key}>
            <writeable-element-example
              location=${key}
              valueFromParent=${this.valueFromParent}
            ></writeable-element-example>
          </div>`;
        });
    }

    return null;
  }

  getSideBarClassName() {
    let className = "sidebar";
    if (this.sideBarClosing) {
      className += " sidebar--closing";
    } else if (!this.sideBarOpen) {
      className += " sidebar--closed";
    }
    return className;
  }

  // Depending on which layout is setting in settings, render the right version of AI chat.
  render() {
    return html`
      ${this.settings.layout === "float"
        ? html`<cds-aichat-container
            .config=${this.config}
            .onError=${this.config.onError}
            .openChatByDefault=${this.config.openChatByDefault ?? undefined}
            .disclaimer=${this.config.disclaimer}
            .disableCustomElementMobileEnhancements=${this.config
              .disableCustomElementMobileEnhancements ?? undefined}
            .debug=${this.config.debug ?? undefined}
            .injectCarbonTheme=${this.config.injectCarbonTheme ?? undefined}
            .aiEnabled=${this.config.aiEnabled ?? undefined}
            .shouldTakeFocusIfOpensAutomatically=${this.config
              .shouldTakeFocusIfOpensAutomatically ?? undefined}
            .namespace=${this.config.namespace ?? undefined}
            .shouldSanitizeHTML=${this.config.shouldSanitizeHTML ?? undefined}
            .header=${this.config.header}
            .layout=${this.config.layout}
            .messaging=${this.config.messaging}
            .isReadonly=${this.config.isReadonly ?? undefined}
            .assistantName=${this.config.assistantName}
            locale=${this.config.locale}
            .homescreen=${this.config.homescreen}
            .launcher=${this.config.launcher}
            .onBeforeRender=${this.onBeforeRender}
            .serviceDeskFactory=${serviceDeskFactory}
            >${this.renderUserDefinedSlots()}${this.renderWriteableElementSlots()}</cds-aichat-container
          >`
        : html``}
      ${this.settings.layout === "sidebar"
        ? html`<cds-aichat-custom-element
            class=${this.getSideBarClassName()}
            .config=${this.config}
            .onError=${this.config.onError}
            .openChatByDefault=${this.config.openChatByDefault ?? undefined}
            .disclaimer=${this.config.disclaimer}
            .disableCustomElementMobileEnhancements=${this.config
              .disableCustomElementMobileEnhancements ?? undefined}
            .debug=${this.config.debug ?? undefined}
            .injectCarbonTheme=${this.config.injectCarbonTheme ?? undefined}
            .aiEnabled=${this.config.aiEnabled ?? undefined}
            .shouldTakeFocusIfOpensAutomatically=${this.config
              .shouldTakeFocusIfOpensAutomatically ?? undefined}
            .namespace=${this.config.namespace ?? undefined}
            .shouldSanitizeHTML=${this.config.shouldSanitizeHTML ?? undefined}
            .header=${this.config.header}
            .layout=${this.config.layout}
            .messaging=${this.config.messaging}
            .isReadonly=${this.config.isReadonly ?? undefined}
            .assistantName=${this.config.assistantName}
            locale=${this.config.locale}
            .homescreen=${this.config.homescreen}
            .launcher=${this.config.launcher}
            .onBeforeRender=${this.onBeforeRender}
            .onViewPreChange=${this.onViewPreChange}
            .onViewChange=${this.onViewChange}
            .serviceDeskFactory=${serviceDeskFactory}
            >${this.renderUserDefinedSlots()}${this.renderWriteableElementSlots()}</cds-aichat-custom-element
          >`
        : html``}
      ${this.settings.layout === "fullscreen" ||
      this.settings.layout === "fullscreen-no-gutter"
        ? html`<cds-aichat-custom-element
            class="fullScreen"
            .config=${this.config}
            .onError=${this.config.onError}
            .openChatByDefault=${this.config.openChatByDefault ?? undefined}
            .disclaimer=${this.config.disclaimer}
            .disableCustomElementMobileEnhancements=${this.config
              .disableCustomElementMobileEnhancements ?? undefined}
            .debug=${this.config.debug ?? undefined}
            .injectCarbonTheme=${this.config.injectCarbonTheme ?? undefined}
            .aiEnabled=${this.config.aiEnabled ?? undefined}
            .shouldTakeFocusIfOpensAutomatically=${this.config
              .shouldTakeFocusIfOpensAutomatically ?? undefined}
            .namespace=${this.config.namespace ?? undefined}
            .shouldSanitizeHTML=${this.config.shouldSanitizeHTML ?? undefined}
            .header=${this.config.header}
            .layout=${this.config.layout}
            .messaging=${this.config.messaging}
            .isReadonly=${this.config.isReadonly ?? undefined}
            .assistantName=${this.config.assistantName}
            locale=${this.config.locale}
            .homescreen=${this.config.homescreen}
            .launcher=${this.config.launcher}
            .onBeforeRender=${this.onBeforeRender}
            .serviceDeskFactory=${serviceDeskFactory}
            >${this.renderUserDefinedSlots()}${this.renderWriteableElementSlots()}</cds-aichat-custom-element
          >`
        : html``}
    `;
  }
}

// Register the custom element if not already defined
declare global {
  interface HTMLElementTagNameMap {
    "demo-app": DemoApp;
  }
}
